// <auto-generated />
namespace PlatformProject.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class TenantGUIDTypeChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TenantGUIDTypeChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201502051249460_TenantGUIDTypeChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
